version: '4.16.3'

services:
  api:
    build: .
    ports:
     - 8002:8002
    volumes:
      - .:/usr/src/app
    command: go run main.go
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - TZ=Asia/Bangkok
    restart: always
    networks:
      database: {}
networks:
  database:
    external: true
